#!/usr/bin/env ruby

require 'rubygems'
require 'yaml'
require 'optparse'
require 'pp'

require 'src/options'
require 'src/transaction'
require 'src/database'
require 'src/dsl'

begin
  # Ensure user is root
  if Process.uid != 0 then
    raise "Must run as root"
  end

  $options = Blanketdb::Options.parse(ARGV)

  case $options[:command]
  when "install"
    require "src/app/install"
    Blanketdb::App::Install.instance.go

    puts ""
    exit
  end

  begin
    # Read confirmation options
    $config = YAML.load_file($options[:config])
  rescue
    raise "Could not load configuration file: #{$options[:config]}"
  end

  # Connect to MySQL
  $database = Blanketdb::Database.instance
  $database.hostname = $config['mysql']['hostname']
  $database.username = $config['mysql']['username']
  $database.password = $config['mysql']['password']
  $database.connect

  case $options[:command]
  when "create"
    require "src/app/create"
    Blanketdb::App::Create.instance.go
  when "snapshot"
    require "src/app/snapshot"
    Blanketdb::App::Snapshot.instance.go
  when "commit"
    require "src/app/commit"
    Blanketdb::App::Commit.instance.go
  when "rollback"
    require "src/app/rollback"
    Blanketdb::App::Rollback.instance.go
  when "drop"
    require "src/app/drop"
    Blanketdb::App::Drop.instance.go
  when "mount"
    require "src/app/mount"
    Blanketdb::App::Mount.instance.go
  when "unmount"
    require "src/app/unmount"
    Blanketdb::App::Unmount.instance.go
  end
rescue
  puts ""
  $stderr.puts "#{$!.to_s.red}"
  puts "Use -v (--verbose) to view entire process".red if !$options[:verbose]
  puts "Rolling back".red
  puts ""

  Blanketdb::Transaction.instance.do_rollback
end

puts ""